/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.devmode.kotlincoroutines.app

import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import java.lang.Thread.sleep

fun main(): Unit = runBlocking {
    launch {
        println(Thread.currentThread().name)
        sleep(1000)
    }

    launch {
        println(Thread.currentThread().name)
        sleep(1000)
    }
}